### ISSUE TITLE
DNS Resolution in docker compose failing

### ISSUE THREAD

**Issue by Keridos** [asciimoo/filtron#8]
Hi there, trying to use this in my own docker-compose file and I noticed that I cannot use the dns name of the target like hostname:8080 in the docker-compose command, even if I have links and depends_on the container whose hostname I would like to use. Would be neat if DNS resolution would work in the command to start filtron.

here is a sample of the portion of the compose-file:
```
  filtron:
    container_name: filtron
    image: dalf/filtron
    hostname: filtron
    restart: always
    network_mode: bridge
    links:
      - searx
    depends_on:
      - searx
    command: -listen 0.0.0.0:4040 -api 0.0.0.0:4041 -target "searx:8888"
    volumes:
      - filtron-data:/etc/filtron:rw
    read_only: true
```
